# Generated by Django 4.2.7 on 2025-05-31 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeproposal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Предложение обмена",
                "verbose_name_plural": "Предложения обмена",
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="exchangeproposal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Электроника"),
                    ("clothing", "Одежда"),
                    ("books", "Книги"),
                    ("furniture", "Мебель"),
                    ("toys", "Игрушки"),
                    ("vehicles", "Транспорт"),
                    ("other", "Другое"),
                ],
                max_length=100,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="condition",
            field=models.CharField(
                choices=[("new", "Новый"), ("used", "Б/у")],
                max_length=10,
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(
                help_text="Подробное описание товара", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на изображение товара",
                null=True,
                verbose_name="URL изображения",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(
                help_text="Краткое описание товара",
                max_length=255,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="ad_receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_proposals",
                to="ads.ad",
                verbose_name="Объявление получателя",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="ad_sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_proposals",
                to="ads.ad",
                verbose_name="Объявление отправителя",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация к предложению",
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("accepted", "Принята"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangeproposal",
            unique_together={("ad_sender", "ad_receiver")},
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(fields=["category"], name="ads_ad_categor_aafbda_idx"),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(fields=["condition"], name="ads_ad_conditi_1d704d_idx"),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(fields=["created_at"], name="ads_ad_created_9f5b83_idx"),
        ),
        migrations.AddIndex(
            model_name="exchangeproposal",
            index=models.Index(fields=["status"], name="ads_exchang_status_de2e30_idx"),
        ),
        migrations.AddIndex(
            model_name="exchangeproposal",
            index=models.Index(
                fields=["created_at"], name="ads_exchang_created_02a71b_idx"
            ),
        ),
    ]
